services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: keboen_bapak_erpdev_app
    restart: always
    expose:
      - "3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_TRUST_HOST: "true"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keboen_shared_network

networks:
  keboen_shared_network:
    external: true

volumes:
  postgres_data: