services:
  db:
    image: postgres:15-alpine
    container_name: keboen_bapak_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - keboen_network

  app:
    build: .
    container_name: keboen_bapak_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_TRUST_HOST: "true"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keboen_network

  nginx:
    image: nginx:alpine
    container_name: keboen_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro # Added :ro (read-only) for safety
    depends_on:
      - app
    networks:
      - keboen_network

networks:
  keboen_network:
    driver: bridge

volumes:
  postgres_data: