services:
  db:
    image: postgres:15-alpine
    container_name: keboen_bapak_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - keboen_network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: keboen_bapak_app
    restart: always
    expose:
      - "3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_TRUST_HOST: "true"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keboen_network

  nginx:
    image: nginx:alpine
    container_name: keboen_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro # Read-only agar aman
      # Buka komentar di bawah jika sudah di VPS untuk SSL
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - app
    networks:
      - keboen_network

# Sertifikat otomatis (Buka komentar di VPS)
  certbot:
   image: certbot/certbot
   container_name: keboen_certbot
   volumes:
     - ./certbot/conf:/etc/letsencrypt
     - ./certbot/www:/var/www/certbot
   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --deploy-hook \"docker kill -s HUP keboen_proxy\"; sleep 12h & wait $${!}; done;'"
   networks:
     - keboen_network

networks:
  keboen_network:
    driver: bridge

volumes:
  postgres_data: